### ISSUE TITLE
Cannot convert from Expression to AbstractElement in ExpressionsTypeProviderTest

### ISSUE THREAD

**Issue by MartinMelikMerkumians** [LorenzoBettini/packtpub-xtext-book-examples#1]
assertType (or to be more precise the typeFor in assertType) in ExpressionsTypeProviderTest complains that it cannot convert from Expression to AbstractElement.

Changing the parameter of typeFor from Expression to AbstractElement solved the problem for me

**Comment by LorenzoBettini** [comment]
Hi
do you mean the dispatch method typeFor in https://github.com/LorenzoBettini/packtpub-xtext-book-examples/blob/7282176fea25878ce4d05f3088ca0ebccd245620/org.example.expressions/src/org/example/expressions/typing/ExpressionsTypeProvider.xtend ?

This works for me; which version of Xtext are you using?

Or are you referring to the code shown in the book?

cheers
Lorenzo

**Comment by MartinMelikMerkumians** [comment]
Hi!

yes I mean the dispatch method, although I came from the book version, which seems to be identical to the one in the GitHub repo. I am using Xtext 2.7.3.

I don't know why, but I get the "Cannot convert from.." error in the Eclipse IDE if I want to use the dispatch in the ExpressionsTypeProviderTest as given in the book.

cheers
Martin

**Comment by MartinMelikMerkumians** [comment]
Hi again,

I have also the same problem with the dispatch method interpret from the ExpressionsInterpreter class

cheers
Martin

**Comment by MartinMelikMerkumians** [comment]
And hi again,

I checked on the issue and it seems that, if only a dispatch method for the Expressions type is given, Xtend does not generate an according Java method accepting AbstractElement. For example, as soon as the dispatch for the Variable type is given the "Cannot convert" error disappears as Xtend needs to generate a method accepting AbstractElement to later delegate to the Expression and Variable type.

cheers
Martin

**Comment by LorenzoBettini** [comment]
Thanks for the updates.
So do you think this is issue is fixed, or is it worthwhile to add in the ERRATA section to add a paragraph about this?

**Comment by MartinMelikMerkumians** [comment]
It is probably worthwhile to add that to the ERRATA section, as it took some time to understand why the code is not working as given in the book. Especially as the Interpreter is not compiling as long as the dispatch interpret(Variable v) is not entered.

**Comment by LorenzoBettini** [comment]
I committed the change in the README containing the errata. Please have a look and feel free to reopen it (or provide a modified version) if the explanation looks wrong.
